name: Go Driver Test

on:
  push:
    branches: [ "master", PG11 ]

  pull_request:
    branches: [ "master", PG11 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.19' ]
        distributions: ['zulu', 'temurin', 'microsoft']
    defaults:
      run:
        working-directory: drivers/golang/age/
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Run apache/age docker image
      run: docker-compose up -d

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Set up Java
      uses: actions/setup-java@v3
        distribution: ${{ matrix.distributions }}
        java-version: '17'
    
    - name: Generate
      run: go generate ./../...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test . -v
